version: "3"

name: "painted-porch"

services:
  painted-porch-frontend:
    networks:
      - painted-porch
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: painted-porch-frontend
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "../frontend:/code/"
    depends_on:
      - painted-porch-backend

  painted-porch-backend:
    networks: 
      - painted-porch
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: painted-porch-backend
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - "../server:/code/"
    depends_on:
      - painted-porch-localstack

  painted-porch-localstack:
    networks:
      - painted-porch
    image: "localstack/localstack:latest"
    container_name: painted-porch-localstack
    ports:
      - "4566:4566"

networks:
  painted-porch: