version: "3"
services:

  painted-porch-frontend:
    networks:
      - painted-porch
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: painted-porch-frontend
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "../frontend:/code/"
    depends_on:
      - painted-porch-backend

  painted-porch-backend:
    networks: 
      - painted-porch
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: painted-porch-backend
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - "../server:/code/"
    depends_on:
      - painted-porch-db

  painted-porch-db:
    networks:
      - painted-porch
    container_name: painted-porch-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-painted-porch:/data/db
    env_file: .env
    command: mongod --quiet

volumes:
  mongo-painted-porch:
networks:
  painted-porch: