version: "3"
services:

  everyday-stoic-frontend:
    networks:
      - everyday-stoic
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: everyday-stoic-frontend
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "../frontend:/code/"
    depends_on:
      - everyday-stoic-backend

  everyday-stoic-backend:
    networks: 
      - everyday-stoic
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: everyday-stoic-backend
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - "../server:/code/"
    depends_on:
      - everyday-stoic-db

  everyday-stoic-db:
    networks:
      - everyday-stoic
    container_name: everyday-stoic-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-everyday-stoic:/data/db
    env_file: .env

volumes:
  mongo-everyday-stoic:
networks:
  everyday-stoic: